// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func jsPageData() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_jsPageData_9d3f`,
		Function: `function __templ_jsPageData_9d3f(){// add the pageData as a window variable
    window.pageData = JSON.parse(document.getElementById('pageData').textContent);
}`,
		Call:       templ.SafeScript(`__templ_jsPageData_9d3f`),
		CallInline: templ.SafeScriptInline(`__templ_jsPageData_9d3f`),
	}
}

func jsInitHtmx() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_jsInitHtmx_6fc9`,
		Function: `function __templ_jsInitHtmx_6fc9(){// This script is used to handle the 404 and 422 errors in the htmx requests.
    document.addEventListener('DOMContentLoaded', function() {
      document.body.addEventListener('htmx:beforeSwap', function (evt) {
        if(evt.detail.xhr.status === 404){
          alert("Error: Not Found (404)");
        } else if (evt.detail.xhr.status === 422) {
          evt.detail.shouldSwap = true;
          evt.detail.isError = false;
        }
      });
    });
}`,
		Call:       templ.SafeScript(`__templ_jsInitHtmx_6fc9`),
		CallInline: templ.SafeScriptInline(`__templ_jsInitHtmx_6fc9`),
	}
}

var _ = templruntime.GeneratedTemplate
