// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: page_type.sql

package dbx

import (
	"context"
)

const getPageTypeHtml = `-- name: GetPageTypeHtml :one
SELECT id, path, level, url, page_type, title, tags, is_in_sitemap, is_searchable, search_vector, full_text, no_cache, created_at, updated_at, meta_description, meta_og_site_name, meta_og_title, meta_og_description, meta_og_url, meta_og_type, meta_og_image, meta_og_image_secure_url, meta_og_image_width, meta_og_image_height, meta_article_publisher, meta_article_section, meta_article_tag, meta_twitter_card, meta_twitter_image, meta_twitter_site, html
FROM page_html
WHERE id = $1
LIMIT 1
`

// get the data for a html page type
func (q *Queries) GetPageTypeHtml(ctx context.Context, id int32) (PageHtml, error) {
	row := q.db.QueryRow(ctx, getPageTypeHtml, id)
	var i PageHtml
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Level,
		&i.Url,
		&i.PageType,
		&i.Title,
		&i.Tags,
		&i.IsInSitemap,
		&i.IsSearchable,
		&i.SearchVector,
		&i.FullText,
		&i.NoCache,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaDescription,
		&i.MetaOgSiteName,
		&i.MetaOgTitle,
		&i.MetaOgDescription,
		&i.MetaOgUrl,
		&i.MetaOgType,
		&i.MetaOgImage,
		&i.MetaOgImageSecureUrl,
		&i.MetaOgImageWidth,
		&i.MetaOgImageHeight,
		&i.MetaArticlePublisher,
		&i.MetaArticleSection,
		&i.MetaArticleTag,
		&i.MetaTwitterCard,
		&i.MetaTwitterImage,
		&i.MetaTwitterSite,
		&i.Html,
	)
	return i, err
}
