// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tailwind.sql

package dbx

import (
	"context"
)

const getCSSClasses = `-- name: GetCSSClasses :many
WITH extracted AS (
    SELECT unnest(regexp_matches(html, 'class="([^"]*)"', 'g')) AS classes
    FROM page_html
)
SELECT DISTINCT unnest(string_to_array(classes, ' ')) AS class
FROM extracted
ORDER BY class
`

// returns a list of css classes found in the html content.
func (q *Queries) GetCSSClasses(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getCSSClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var class string
		if err := rows.Scan(&class); err != nil {
			return nil, err
		}
		items = append(items, class)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
